require('dotenv').config();

let CONFIG = {} 

CONFIG.PORT = process.env.PORT || '9008';
CONFIG.DB_DIALECT = process.env.DB_DIALECT || 'mongo';
CONFIG.DB_HOST = process.env.DB_HOST || 'localhost';
CONFIG.DB_PORT = process.env.DB_PORT || '37087';

CONFIG.DB_NAME = process.env.DB_NAME || 'notifications_DB';
CONFIG.DB_USER = process.env.DB_USER || 'notifications';
CONFIG.DB_PASSWORD = process.env.DB_PASSWORD || 'sdbmnve8973298r246&&#';

CONFIG.AWS_LYNKBUILTY_ACCESS_KEY = process.env.AWS_LYNKBUILTY_ACCESS_KEY  ||  "AKJUINUBBHXUPEXY"
CONFIG.AWS_LYNKBUILTY_SECRET_KEY =process.env.AWS_LYNKBUILTY_SECRET_KEY  ||  "4i8AyqvfvjlkvfxsdcaDhiLobm"



CONFIG.EMAIL_ID = process.env.EMAIL_ID  || "support@gmail.com"
CONFIG.SUPPORT_MOBILE_NUMBER = process.env.SUPPORT_MOBILE_NUMBER  || "03340586958"

CONFIG.TWILIO_ACCOUNT_SID= process.env.TWILIO_ACCOUNT_SID || "AC0fbsadvaebrnth7f23928a"
CONFIG.TWILIO_AUTH_TOKEN= process.env.TWILIO_AUTH_TOKEN || "f0b3asVWEBNHLKEWENJQDIOf59"
CONFIG.TWILIO_PHONE_NUMBER= process.env.TWILIO_PHONE_NUMBER || "+12454646446"
CONFIG.VAPID_PUBLIC_KEY= process.env.VAPID_PUBLIC_KEY || "EWRGTRJNSKJafhGBVEWASLCMASDLVFEW9EE9Wf"
CONFIG.VAPID_PRIVATE_KEY= process.env.VAPID_PRIVATE_KEY || "aSCIDVJDFIFJNIDNNGK2g13I"
module.exports = CONFIG;
